name: SuperwallKit
options:
  bundleIdentifer: com.superwall

packages:
  SuperCEL:
    url: https://github.com/superwall/SuperCEL-iOS
    exact: "0.1.9"

targets:
  SuperwallKit:
    scheme:
      testTargets:
        - name: SuperwallKitTests
      commandLineArguments:
        SUPERWALL_UNIT_TESTS: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.superwall.SuperwallKit"
    info:
      path: SuperwallKit.xcodeproj/SuperwallKit_Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "FMWK"
        CFBundleShortVersionString: "1.0"
        CFBundleSignature: ????
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSPrincipalClass: ""
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Sources/]
    dependencies:
      - package: SuperCEL
  SuperwallKitTests:
    scheme: {}
    sources: [Tests/]
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: SuperwallKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.superwall.SuperwallTests"

    info:
      path: SuperwallKit.xcodeproj/SuperwallTests_Info.plist
      properties:
        CFBundleDevelopmentRegion: en
