name: Emerge Head Build Upload

on:
  pull_request:
    branches:
      - master  # PRs targeting the master branch

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Git Checkout
        uses: actions/checkout@v3

      # Generate Xcode project with XcodeGen
      - name: Run XcodeGen
        uses: xavierLowmiller/xcodegen-action@1.2.3

      # Build the iOS release bundle using xcodebuild
      - name: Generate iOS release bundle
        run: |
          xcodebuild -project SuperwallKit.xcodeproj \
          -scheme SuperwallKit \
          -sdk iphoneos \
          -configuration Release \
          -archivePath ./build/SuperwallKit.xcarchive archive

      # Zip the xcarchive for upload
      - name: Zip the xcarchive
        run: zip -r ./build/SuperwallKit.xcarchive.zip ./build/SuperwallKit.xcarchive

      # Upload head build to Emerge (for PR comparison)
      - name: Upload Head Build to Emerge
        uses: EmergeTools/emerge-upload-action@v1.1.0
        with:
          artifact_path: ./build/SuperwallKit.xcarchive.zip
          emerge_api_key: ${{ secrets.EMERGE_API_KEY }}
          build_type: release
          branch: ${{ github.ref_name }}  # The branch name
          sha: ${{ github.sha }}  # The commit SHA
          repoName: ${{ github.repository }}  # The repository name
          filename: SuperwallKit.xcarchive.zip
          tag: pull-request  # Tag it as a PR build
          baseSha: ${{ github.event.pull_request.base.sha }}  # The base SHA for comparison
          prNumber: ${{ github.event.pull_request.number }}  # Include PR number for tracking
          previousSha: ${{ github.event.before }}  # Include previous commit SHA (HEAD^)
