name: Emerge Tools Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2
#      - name: Build XCFramework
#        run: sh build.sh

      - name: Upload artifact to Emerge
        uses: EmergeTools/emerge-upload-action@v1.1.0
        with:
          artifact_path: ./build/SuperwallKit.xcarchive.zip
          emerge_api_key: ${{ secrets.EMERGE_API_KEY }}
          build_type: release
