name: Emerge Tools Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Git Checkout
        uses: actions/checkout@v3

      # Generate Xcode project with XcodeGen
      - name: Run XcodeGen
        uses: xavierLowmiller/xcodegen-action@1.2.3

      # Build the iOS release bundle using xcodebuild
      - name: Generate iOS release bundle
        run: |
          xcodebuild -project SuperwallKit.xcodeproj \
          -scheme SuperwallKit \
          -sdk iphoneos \
          -configuration Release \
          -archivePath ./build/SuperwallKit.xcarchive archive

      # Zip the xcarchive for upload
      - name: Zip the xcarchive
        run: zip -r ./build/SuperwallKit.xcarchive.zip ./build/SuperwallKit.xcarchive

      # Upload base build to Emerge
      - name: Upload Base Build to Emerge
        uses: EmergeTools/emerge-upload-action@v1.1.0
        with:
          artifact_path: ./build/SuperwallKit.xcarchive.zip
          emerge_api_key: ${{ secrets.EMERGE_API_KEY }}
          build_type: release
