name: Run Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'project.yml'
      - '**/*.swift'
      - '!Examples/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.5.0"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
